# we are extending everything from tomcat:8.0 image ...
FROM tomcat:8.5.47-jdk8-openjdk
MAINTAINER MCA-implementer
# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat
COPY /target/BALENQ-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/