apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-enquiry-service
  labels:
    app: balance-enquiry-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balance-enquiry-app
  template:
    metadata:
      labels:
        app: balance-enquiry-app
    spec:
      containers:
        - name: balance-enquiry-service
          image: mca:balance-enquiry-v1
---
apiVersion: v1
kind: Service
metadata:
  name: balance-enquiry-service
spec:
  type: NodePort
  selector:
    app: balance-enquiry-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31100