apiVersion: apps/v1
kind: Deployment
metadata:
  name: mip-service
  labels:
    app: mip-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mip-app
  template:
    metadata:
      labels:
        app: mip-app
    spec:
      containers:
        - name: mip-service
          image: mca:mip-v1
---
apiVersion: v1
kind: Service
metadata:
  name: mip-service
spec:
  type: NodePort
  selector:
    app: mip-app
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 31200